#!/usr/bin/with-contenv /bin/sh

echo "Waiting for web server to start"
s6-svwait -u /var/run/s6/services/httpd

echo "Starting shibboleth"
# shibd -fF -u nginx -g nginx
# pidfile=/var/run/shibboleth/shibd.pid
# [ -d /var/run/shibboleth ] || mkdir /var/run/shibboleth
# shibd -F
shibd -u root -g root -fF -c /etc/shibboleth/shibboleth2.xml -w 10
